version: '3.8'
services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins
    container_name: jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins: