name: Docker In Jenkins CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Build
        run: |
          docker build -t dturan/jenkins-on-docker ./Jenkins     

      - name: Docker Push
        run: |
          docker push dturan/jenkins-on-docker:latest
